accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/', views.signup, name='signup'),
    url(r'^login/', views.login_view, name='login'),
    url(r'^logout/', views.logout_view, name='logout'),
]

activities/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'activities'

urlpatterns = [
    path('math', views.math, name='math'),
    path('colors', views.colors, name='colors'),
    path('comprehension', views.comprehension, name='comprehension'),
    path('rhyme', views.rhyme, name='rhyme'),
]

studybuddy/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path

import activities.views as act_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', act_views.index, name='index'),
    path('activities/', include('activities.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

activities/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout

def signup(request):
	if request.method=='POST':
		if request.POST['password1'] == request.POST['password2']:
			# check if the username has already been taken
			try:
				user = User.objects.get(username=request.POST['username'])
				return render(request, 'accounts/signup.html', {'error' : "Username has already been taken"})
			except User.DoesNotExist:
				user = User.objects.create_user(
					username=request.POST['username'], 
					password=request.POST['password1'],
					email=request.POST['email'])
				# logging in as the user who signed up, can't access admin page now
				# login(request, user) 
				return render(request, 'accounts/signup.html', {'error' : "New User created"})
		else:
			return render(request, 'accounts/signup.html', {'error' : "Paswords didn't match"})
	else:
		return render(request, 'accounts/signup.html')

def login_view(request):
	if request.method=='POST':
		user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
		if user is not None:
			login(request, user)
			# since it is not a permanent field in the form, created only when there is 'next'
			if 'next' in request.POST:
				return redirect(request.POST['next'])
			return redirect('index')
		else:
			return render(request, 'accounts/login.html', {'error' : "Account does not exist OR Username and Password didn't match"})
	else:
		return render(request, 'accounts/login.html')

def logout_view(request):
	if request.method == 'POST':
		logout(request)
		return redirect('index')

activities/views.py
from django.shortcuts import render

def index(request):
	# for study buddy homepage
    return render(request, 'activities/index.html')

def math(request):
	return render(request, 'activities/math.html')

def colors(request):
	return render(request, 'activities/colors.html')

def comprehension(request):
	return render(request, 'activities/english.html')

def rhyme(request):
	return render(request, 'activities/rhymes.html')

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}


{% block head %}

<title>Login</title>
<link rel="stylesheet" href="{% static 'css/login.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/shoelace-css/1.0.0-beta16/shoelace.css">

{% endblock %}

{% block content %}

<section id="hero" style=" width: 100%;
height: 100vh; 
background: url(https://i.pinimg.com/originals/45/e5/89/45e589d94ea6221f88dd589609628a5e.jpg) top center;
opacity: 0.95;
background-size: contain;
background-repeat: no-repeat;">
	<h1 style="font-weight: 1000; text-align: center; font-size: 80px;">Log In!</h1>

	{% if error %}
	{{ error }}
	<br><br>
	{% endif %}

	<!-- all instructions given in signup.html -->
	<form method="POST" action="{% url 'accounts:login' %}" style="width: 175px; margin-left: 870px; font-weight: 1000; margin-top: -70px; font-size: larger; text-align: center;">
		{% csrf_token %}

		{% if request.GET.next %}
		<input type="hidden" name="next" value={{ request.GET.next }} >
		{% endif %}

		Username: <br>
		<input type="text" name="username">
		<br> Password: <br>
		<input type="password" name="password">
		<br><br>
		<input class="btn btn-primary" type="submit" style="font-weight: 1000; font-size: 20px;">
	</form>

</section>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}

<section id="hero" style=" width: 100%;
height: 100vh; 
background: url(https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9780/3758/9780375802799.jpg) top center;
opacity: 0.85;
background-size: contain;
background-repeat: no-repeat;">

	<div id="container" style="font-weight: 1000; margin-left: 600px; margin-bottom: 10px;">

		<h1 style="font-size: 60px; margin-left: -50px;">Sign Up!</h1>

		{% if error %}
		{{ error }}
		<br><br>
		{% endif %}

		<!-- url format is '<app_name>:<url_name>' url_name is given with url regex -->
		<!-- in form action 'signup' is the name of the url we go to on submit (specified in urls.py)  -->
		<form method="POST" action="{% url 'accounts:signup' %}" style="width: 200px ;margin-top: 220px; margin-left: -20px; color: rgb(157, 255, 0);font-size: larger; text-align: center;">
			{% csrf_token %}
			Parent Name: <br>
			<input type="text" name="username">
			<br> Password: <br>
			<input type="password" name="password1">
			<br> Confirm Password: <br>
			<input type="password" name="password2">
			<br> Email ID: <br>
			<input type="email" name="email">
			<br> Child's Name <br>
			<input type="text" name="child_name">
			<br> Child's Age <br>
			<input type="text" name="child_age">
			<br><br>
			<input class="btn btn-primary" type="submit">
		</form>
	</div>
</section>

{% endblock %}

activities/templates/activities/colors.html
{% extends 'base.html' %}
{% load static %}

{% block head %}

<link rel="stylesheet" href="{% static 'css/colors.css' %}">
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap" rel="stylesheet">

{% endblock %}

{% block content %}
<div class="container">
	<h1 id="see" align='center'>Thomas and Colors!</h1>
    <h1 align='center'>Select Pictures Having Red Color!</h1>
    <br>

  <table id="tab" align ='center'>
    <tr>
      <td> <img id="one"src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Strawberries.jpg/1200px-Strawberries.jpg" alt="LOADING IMAGE" width="190" height="190"></td>
      <td ><img id="two"src="https://ae01.alicdn.com/kf/HTB1GEBwbjfguuRjy1zeq6z0KFXaS/1pcs-Doraemon-Nobi-Nobita-Toy-figure-Nobita-Pvc-Action-Figures-Toys-15cm-Box-Packaged-Retail-Free.jpg_640x640.jpg" alt="LOADING IMAGE" width="190" height="190"></td>
      <td><img id="three"src="https://static.independent.co.uk/s3fs-public/styles/story_medium/public/indy100/bkxLRrwYqgW/25426-1yh1bw8.jpg" alt="LOADING IMAGE" width="190" height="190"></td>
    </tr>

    <tr>
      <td><img id="four"src="https://www.bourncreative.com/wp-content/uploads/2010/10/black.jpg" alt="LOADING IMAGE" width="190" height="190"></td>
      <td><img id="five"src="https://images-na.ssl-images-amazon.com/images/I/61iQ1ph8o4L._SL1000_.jpg" alt="LOADING IMAGE" width="190" height="190"></td>
      <td><img id="six"src="https://cdn1.vectorstock.com/i/1000x1000/56/25/star-icon-yellow-sign-object-vector-24495625.jpg" alt="LOADING IMAGE" width="190" height="190"></td>
    </tr>

    <tr>
      <td><img id="seven"src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Bob_the_Builder_ride%2C_Sainsbury%27s_north_London.jpg/789px-Bob_the_Builder_ride%2C_Sainsbury%27s_north_London.jpg" alt="LOADING IMAGE" width="190" height="190"></td>
      <td><img id="eight"src="http://www.vespa.in/images/ourchoice/Vespa_red_banner101.png" alt="LOADING IMAGE" width="190" height="190"></td>
      <td><img id="nine"src="https://images-na.ssl-images-amazon.com/images/I/71lnQdxlWzL._SX466_.jpg" alt="LOADING IMAGE" width="190" height="190"></td>
    </tr>

  </table>

<div id="d"class="text-center"><button class="btn btn-primary btn-lg" type="button">Get Marks!</button></div>

</div>
<script src = "{% static 'js/colors.js' %}"></script>

<h1 id="fo" align='center'>Your Marks: <span id="myText"></span></h1>

{% endblock %}

activities/templates/activities/english.html
{% extends 'base.html' %}
{% load static %}

{% block head %}

<title>Thomas and Words</title>
<link rel="stylesheet" href="{% static 'css/english.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/shoelace-css/1.0.0-beta16/shoelace.css">

{% endblock %}

{% block content %}

<section id="hero">
    <div class="container">
        <h1>Thomas and Words</h1>
        <div class="app">
            <h3>Comprehension Practice</h3>
            <button id="listen-comprehension" title="Start Listening">Listen</button>
            <div class="input-single">
                <textarea id="note-textarea" type="reset" placeholder="Answer" rows="1"></textarea>
            </div>
            <button id="bol-question" title="bolo question">Listen to Question</button>
            <button id="start-record-btn" title="Start Recording">Start Recognition</button>
            <button id="check-answer" title="check answer">Evaluate</button>
        </div>
    </div>
</section>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="text/javascript" src="{% static 'js/script.js' %}"></script>
<script type="text/javascript" src="{% static 'js/speech_recognition.js' %}"></script>

{% endblock %}

activities/templates/activities/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}

<link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/shoelace-css/1.0.0-beta16/shoelace.css">

{% endblock %}


{% block content %}

<section id="hero">
	<div class="hero-container container">
		<h1>Study Buddy!</h1>


		<h2>Your child's best friend <3</h2>

				{% if user.is_authenticated %}
				<h3>You are signed in as {{ request.user.username }}</h3>
				{% endif %}
	</div>

</section>

{% endblock %}

activities/templates/activities/math.html
{% extends 'base.html' %}
{% load static %}

{% block head %}

<link rel="stylesheet" type="text/css" href="{% static 'css/math.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/shoelace-css/1.0.0-beta16/shoelace.css">

{% endblock %}

{% block content %}

<section id="hero">
	<div class="hero-container container">
		<h1>Thomas and Math</h1><br>
		<h2 style="color: #f4c842">Let Us Have Some Fun With Numbers!<br>Perform the following operations. Best Of Luck! <span class="glyphicon glyphicon-thumbs-up"></span></h2>
		<div id="div1" style="font-weight: 900; font-size: 20px">
			<div class="app"> 
				<div class="input-single">
					<textarea id="note-textarea" type="reset" placeholder="Answer" rows="1"></textarea>
				</div>   
				<button id="start-record-btn">Speak</button>
				<button id="pause-record-btn" title="Pause Recording">Submit</button>
			</div>
		</div>
	</div>
</section>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="text/javascript" src="{% static 'js/math.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
<script src="{% static 'js/speech_recognition.js' %}"></script>

{% endblock %}

activities/templates/activities/rhymes.html
{% extends 'base.html' %}
{% load static %}

{% block head %}

<title>Thomas and Rhymes</title>
<link rel="stylesheet" href="{% static 'css/rhyme.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/shoelace-css/1.0.0-beta16/shoelace.css">

{% endblock %}

{% block content %}
<section id="hero_rhyme">
    <div class="container">
        <h1>Thomas and Rhymes</h1>
        <div class="app">
            <h3>Let's recite a rhyme together!</h3>
            <button id="listen-rhyme" title="Start Listening">Listen</button>
            <div class="input-single">
                <textarea id="note-textarea" type="reset" placeholder="Answer" rows="1"></textarea>
            </div>
            <!-- <button id="bol-question" title="bolo question">Listen to Question</button> -->
            <button id="start-record-btn" title="Start Recording">Start Recognition</button>
            <button id="check-answer" title="check answer">Evaluate</button>
        </div>
    </div>
</section>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="text/javascript" src="{% static 'js/rhyme.js' %}"></script>
<script type="text/javascript" src="{% static 'js/speech_recognition.js' %}"></script>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>Study Buddy</title>
  {% block head %}
  {% endblock %}
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <script src="https://kit.fontawesome.com/26ef8f5d5d.js" crossorigin="anonymous"></script>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Study Buddy</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Activities
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="/activities/colors">Thomas & Colors</a>
          <a class="dropdown-item" href="/activities/math">Thomas & Math</a>
          <a class="dropdown-item" href="/activities/comprehension">Thomas & Words</a>
          <a class="dropdown-item" href="/activities/rhyme">Thomas & Rhymes</a>
        </div>
      </li>
      <ul class="navbar-nav">
        {% if user.is_authenticated %}
          <li><a class="nav-link" href="#">Parent</a></li>
          <li><a class="nav-link" href="#" onClick="document.getElementById('logout').submit()">LogOut</a></li>
          <form id="logout" method="POST" action="{% url 'accounts:logout' %}">
            {% csrf_token %}
            <input type="hidden">
          </form>

        {% else %}
          <li><a class="nav-link" href="{% url 'accounts:login' %}">Login</a></li>
          <li><a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a></li>
        {% endif %}
      </ul>
    </ul>
  </div>
</nav>

<br>

<div class="container">
	{% block content %}
	{% endblock %}
</div>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>